# Generated by Django 3.2.3 on 2021-06-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_mainphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='contents',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='post',
            name='mainphoto',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='사진첨부'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postname',
            field=models.CharField(max_length=50, verbose_name='제목'),
        ),
    ]
