# Generated by Django 3.2.3 on 2021-06-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210608_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='write',
            field=models.TextField(null=True, verbose_name='세부내용'),
        ),
    ]
