# Generated by Django 3.2.3 on 2021-06-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_post_write'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='jop',
            field=models.CharField(max_length=50, null=True, verbose_name='직업'),
        ),
    ]
