# Generated by Django 3.2.3 on 2021-06-29 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_post2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post2',
        ),
    ]
